import type { TeachingOperationId } from "@/components/teaching/teaching-operation-data";
import type {
  TeachingOperationActionDefinition,
  TeachingOperationActionId,
  TeachingOperationActionSlot,
} from "./teaching-operations-store";

// Server-side action catalog for teaching operations: the localized definition
// for each (operation, action-slot). Extracted (Phase 3 decomposition) from the
// operations store as self-contained data plus its builder. The store types are a
// type-only import, so this module has no runtime import cycle with the store.

function action(
  actionId: TeachingOperationActionId,
  zhText: string,
  enText: string,
  table: string,
): TeachingOperationActionDefinition {
  return {
    actionId,
    displayMessage: {
      "zh-CN": zhText,
      "en-US": enText,
    },
    table,
  };
}

export const actionDefinitions: Record<
  TeachingOperationId,
  Record<TeachingOperationActionSlot, TeachingOperationActionDefinition>
> = {
  "course-settings": {
    primary: action(
      "save-course-settings",
      "课程设置已由服务端持久化。",
      "Course settings persisted by the server.",
      "course_settings",
    ),
    secondary: action(
      "preview-student-view",
      "学生端预览已由服务端生成。",
      "Student preview generated by the server.",
      "student_previews",
    ),
  },
  agents: {
    primary: action(
      "save-agent-plan",
      "智能体方案已写入服务端。",
      "Agent plan saved by the server.",
      "agent_plans",
    ),
    secondary: action(
      "run-permission-preflight",
      "权限预检已由后端完成。",
      "Permission preflight completed by the backend.",
      "permission_preflights",
    ),
  },
  "knowledge-base": {
    primary: action(
      "sync-knowledge-index",
      "知识库索引已同步到服务端。",
      "Knowledge index synced to the server.",
      "knowledge_indexes",
    ),
    secondary: action(
      "register-knowledge-source",
      "知识来源已登记并写入教师审核队列。",
      "Knowledge source registered in the teacher review queue.",
      "knowledge_resource_reviews",
    ),
  },
  content: {
    primary: action(
      "publish-course-content",
      "课程内容发布记录已保存。",
      "Course content publish record saved.",
      "course_content",
    ),
    secondary: action(
      "generate-unit-draft",
      "单元草稿已由后端生成。",
      "Unit draft generated by the backend.",
      "unit_drafts",
    ),
  },
  admins: {
    primary: action(
      "save-admin-settings",
      "管理员设置已保存并写入审计记录。",
      "Admin settings saved with an audit record.",
      "admin_settings",
    ),
    secondary: action(
      "send-collaboration-invite",
      "协作邀请已写入服务端发件队列。",
      "Collaboration invite written to the server outbox.",
      "collaboration_invites",
    ),
  },
  students: {
    primary: action(
      "sync-roster",
      "学生名单已同步到服务端。",
      "Roster synced to the server.",
      "student_rosters",
    ),
    secondary: action(
      "generate-group-suggestions",
      "分组建议已保存等待教师确认。",
      "Group suggestions saved for teacher confirmation.",
      "group_suggestions",
    ),
  },
  "data-export": {
    primary: action(
      "create-export-manifest",
      "导出清单文件已由服务端生成。",
      "Export manifest file generated by the server.",
      "export_manifests",
    ),
    secondary: action(
      "validate-redaction-scope",
      "脱敏范围已由后端校验通过。",
      "Redaction scope validated by the backend.",
      "redaction_checks",
    ),
  },
  dashboard: {
    primary: action(
      "refresh-dashboard",
      "数据看板已从后端刷新。",
      "Dashboard refreshed from the backend.",
      "dashboard_refreshes",
    ),
    secondary: action(
      "lock-daily-snapshot",
      "日报快照已锁定到服务端。",
      "Daily snapshot locked to the server.",
      "dashboard_snapshots",
    ),
  },
  "quiz-board": {
    primary: action(
      "refresh-quiz-board",
      "测验看板已从后端刷新。",
      "Quiz board refreshed from the backend.",
      "quiz_board_refreshes",
    ),
    secondary: action(
      "flag-low-quality-items",
      "低质题复核标记已保存。",
      "Low-quality item review flag saved.",
      "quiz_item_reviews",
    ),
  },
  grading: {
    primary: action(
      "save-review-queue",
      "批改队列已保存到服务端。",
      "Review queue saved to the server.",
      "grading_queues",
    ),
    secondary: action(
      "generate-ai-feedback",
      "AI 反馈建议已由后端生成。",
      "AI feedback suggestions generated by the backend.",
      "ai_feedback_suggestions",
    ),
  },
  "invite-code": {
    primary: action(
      "generate-invite-code",
      "邀请码已生成并保存，等待教师发布。",
      "Invite code generated and saved for teacher publishing.",
      "invite_codes",
    ),
    secondary: action(
      "publish-invite-code",
      "邀请码已发布到班级加入入口。",
      "Invite code published to the class join entry.",
      "invite_code_publications",
    ),
  },
};
